version: "3"
services: 
  scrayper:
    image: selenium/standalone-chrome:4.0.0-beta-1-prerelease-20201208
    ports: 
      - '4444:4444'
    volumes:
      - '/dev/shm:/dev/shm'
    container_name: football_scrayper

  web:
    build: . 
    ports:
      - '2222:8888'
    volumes:
      - './work/:/work/'
    container_name: football_web

  # 参考URL https://qiita.com/kei0919/items/f6f696169c92c936374c