rename_dict = {
    'Player': 'Player',
    'Nation': 'Nation',
    'Pos': 'Pos',
    'Squad': 'Squad',
    'Age': 'Age',
    'Born': 'Born',
    'MP_Playing Time': 'MP Playing Time',
    'Starts_Playing Time': 'Starts',
    'Min_Playing Time': 'Min Playing Time',
    '90s_Playing Time': '90s Playing Time',
    'Gls_Performance': 'Goal',
    'Ast_Performance': 'Assist',
    'G+A_Performance': 'Goal+Assist',
    'G-PK_Performance': 'Goal-PK',
    'PK_Performance': 'PK',
    'PKatt_Performance': 'PK Attempt',
    'CrdY_Performance': 'Yellow Card',
    'CrdR_Performance': 'Red Card',
    'xG_Expected': 'xG',
    'npxG_Expected': 'npxG',
    'xAG_Expected': 'xA',
    'npxG+xAG_Expected': 'npxG+xA',
    'PrgC_Progression': 'Progressive Carry',
    'PrgP_Progression': 'Progressive Pass',
    'PrgR_Progression': 'Progressive Receive',
    'Gls_Per 90 Minutes': 'Goal Per90',
    'Ast_Per 90 Minutes': 'Assist Per90',
    'G+A_Per 90 Minutes': 'G+A Per90',
    'G-PK_Per 90 Minutes': 'G-PK Per90',
    'G+A-PK_Per 90 Minutes': 'G+A-PK Per90',
    'xG_Per 90 Minutes': 'xG Per90',
    'xAG_Per 90 Minutes': 'xA Per90',
    'xG+xAG_Per 90 Minutes': 'xG+xA Per90',
    'npxG_Per 90 Minutes': 'npxG Per90',
    'npxG+xAG_Per 90 Minutes': 'npxG+xA Per90',
    '90s': '90s',
    'Touches_Touches': 'Touches',
    'Def Pen_Touches': 'Def-Pen\nTouch',
    'Def 3rd_Touches': 'Def-3rd\nTouch',
    'Mid 3rd_Touches': 'Mid-3rd\nTouch',
    'Att 3rd_Touches': 'Att-3rd\nTouch',
    'Att Pen_Touches': 'Att-Pen\nTouch',
    'Live_Touches': 'Live Touch',
    'Att_Take-Ons': 'Dribble Attempt',
    'Succ_Take-Ons': 'Successful\nDribble',
    'Succ%_Take-Ons': 'Successful%\nDribble',
    'Tkld_Take-Ons': 'Tackled\nDribble',
    'Tkld%_Take-Ons': 'Tackled%\nDribble',
    'Carries_Carries': 'Carries',
    'TotDist_Carries': 'Total-Distance\nCarries',
    'PrgDist_Carries': 'Progressive-Distance\nCarries',
    'PrgC_Carries': 'Progressive\nCarries',
    '1/3_Carries': '1/3 Carries',
    'CPA_Carries': 'Pena Carries',
    'Mis_Carries': 'Miscontrol',
    'Dis_Carries': 'Ball Lost',
    'Rec_Receiving': 'Pass Receiving',
    'PrgR_Receiving': 'Progressive-Pass\nReceiving',
    'SCA_SCA': 'Shot Create',
    'SCA90_SCA': 'Shot Create90',
    'PassLive_SCA Types': 'Shot Create\nBy PassLive',
    'PassDead_SCA Types': 'Shot Create\nBy PassDead',
    'TO_SCA Types': 'Shot Create\nBy Dribble',
    'Sh_SCA Types': 'Shot Create\nBy Shot',
    'Fld_SCA Types': 'Shot Create\nBy Fouls',
    'Def_SCA Types': 'Shot Create\nBy Deffense',
    'GCA_GCA': 'Goal Create',
    'GCA90_GCA': 'Goal Create90',
    'PassLive_GCA Types': 'Goal Create\nBy PassLive',
    'PassDead_GCA Types': 'Goal Create\nBy PassDead',
    'TO_GCA Types': 'Goal Create\nBy Dribble',
    'Sh_GCA Types': 'Goal Create\nBy Shot',
    'Fld_GCA Types': 'Goal Create\nBy Fouls',
    'Def_GCA Types': 'Goal Create\nBy Deffense',
    'Cmp_Total': 'Pass Complete',
    'Att_Total': 'Pass Attempt',
    'Cmp%_Total': 'Pass Complete%',
    'TotDist_Total': 'Pass Total Distance',
    'PrgDist_Total': 'Progressive-Pass\nTotal Distance',
    'Cmp_Short': 'Short-Pass\nComplete',
    'Att_Short': 'Short-Pass\nAttempt',
    'Cmp%_Short': 'Short-Pass\nComplete%',
    'Cmp_Medium': 'Medium-Pass\nComplete',
    'Att_Medium': 'Medium-Pass\nAttempt',
    'Cmp%_Medium': 'Medium-Pass\nComplete%',
    'Cmp_Long': 'Long-Pass\nComplete',
    'Att_Long': 'Long-Pass\nAttempt',
    'Cmp%_Long': 'Long-Pass\nComplete%',
    'Ast': 'Assist',
    'xAG': 'xAG',
    'xA': 'xA',
    'A-xAG': 'A-xAG',
    'KP': 'KP',
    '1/3': '1/3',
    'PPA': 'PPA',
    'CrsPA': 'CrsPA',
    'PrgP': 'PrgP',
    'Gls_Standard': 'Gls_Standard',
    'Sh_Standard': 'Sh_Standard',
    'SoT_Standard': 'SoT_Standard',
    'SoT%_Standard': 'SoT%_Standard',
    'Sh/90_Standard': 'Sh/90_Standard',
    'SoT/90_Standard': 'SoT/90_Standard',
    'G/Sh_Standard': 'G/Sh_Standard',
    'G/SoT_Standard': 'G/SoT_Standard',
    'Dist_Standard': 'Dist_Standard',
    'FK_Standard': 'FK_Standard',
    'PK_Standard': 'PK_Standard',
    'PKatt_Standard': 'PKatt_Standard',
    'npxG/Sh_Expected': 'npxG/Sh_Expected',
    'G-xG_Expected': 'G-xG_Expected',
    'np:G-xG_Expected': 'Goal-xG(non-pen)',
    'Att': 'Att',
    'Live_Pass Types': 'Live Pass',
    'Dead_Pass Types': 'Dead Pass',
    'FK_Pass Types': 'FK Pass',
    'TB_Pass Types': 'Throwgh Pass',
    'Sw_Pass Types': 'Switch Pass',
    'Crs_Pass Types': 'Cross',
    'TI_Pass Types': 'TI Pass',
    'CK_Pass Types': 'CK Pass',
    'In_Corner Kicks': 'In_Corner Kicks',
    'Out_Corner Kicks': 'Out_Corner Kicks',
    'Str_Corner Kicks': 'Str_Corner Kicks',
    'Cmp_Outcomes': 'Cmp_Outcomes',
    'Off_Outcomes': 'Off_Outcomes',
    'Blocks_Outcomes': 'Block',
    '2CrdY_Performance': '2CrdY_Performance',
    'Fls_Performance': 'Fls_Performance',
    'Fld_Performance': 'Fld_Performance',
    'Off_Performance': 'Off_Performance',
    'Crs_Performance': 'Crs_Performance',
    'Int_Performance': 'Intercept',
    'TklW_Performance': 'Tackle Win',
    'PKwon_Performance': 'PKwon_Performance',
    'PKcon_Performance': 'PKcon_Performance',
    'OG_Performance': 'OG_Performance',
    'Recov_Performance': 'Recovery',
    'Won_Aerial Duels': 'Won Aerial Duels',
    'Lost_Aerial Duels': 'Lost Aerial Duels',
    'Won%_Aerial Duels': 'Won% Aerial Duels',
    'PPM_Team Success': "Points per Match",
    'onG_Team Success': "Goals Scored on pitch",
    'onGA_Team Success': "Goals Allowed on pitch",
    '+/-_Team Success': "Plus/Minus",
    '+/-90_Team Success': "Plus/Minus Per90",
    'On-Off_Team Success': "Plus/Minus Net Per90",
    'onxG_Team Success (xG)': "xG (on pitch)",
    'onxGA_Team Success (xG)': "xGA (on pitch)",
    'xG+/-_Team Success (xG)': "xG Plus/Minus",
    'xG+/-90_Team Success (xG)': "xG Plus/Minus Per90",
    'On-Off_Team Success (xG)': "xG On-Off"
}