convert_nation_dict = {
    "Argentina": "ARG",
    "Algeria": "ALG",
    "Austria": "AUT",
    "Brazil": "BRA",
    "Belgium": "BEL",
    "Central African Republic": "CTA",
    "Chile": "CHI",
    "Colombia": "COL",
    "Cote d'Ivoire": "CIV",
    "Croatia": "CRO",
    "Czech Republic": "CZE",
    "Denmark": "DEN",
    "France": "FRA",
    "England": "ENG",
    "Germany": "GER",
    "Ghana": "GHA",
    "Guinea": "GUI",
    "Portugal": "POR",
    "Italy": "ITA",
    "Iran": "IRN",
    "Ireland":"IRL",
    "Japan": "JPN",
    "Kosovo": "KVX",
    "Kenya": "KNY",
    "Poland": "POL",
    "Russia": "RUS",
    "Mali": "MLI",
    "Mexico": "MEX",
    "Morocco": "MAR",
    "Netherlands": "NED",
    "Norway": "NOR",
    "Nigeria": "NGA",
    "Scotland": "SCO",
    "Serbia": "SER",
    "Senegal": "SEN",
    "Spain": "ESP",
    "Slovakia": "SVK",
    "Switzerland": "SUI",
    "Turkey": "TUR",
    "Tunisia": "TUN",
    "United States": "USA"
}