cols = [
    'Player',
    'Nation',
    'Pos',
    'Squad',
    'Age',
    'Born',
    'MP_Playing Time',
    'Starts_Playing Time',
    'Min_Playing Time',
    '90s_Playing Time',
    'Gls_Performance',
    'Ast_Performance',
    'G+A_Performance',
    'G-PK_Performance',
    'PK_Performance',
    'PKatt_Performance',
    'CrdY_Performance',
    'CrdR_Performance',
    'xG_Expected',
    'npxG_Expected',
    'xAG_Expected',
    'npxG+xAG_Expected',
    'PrgC_Progression',
    'PrgP_Progression',
    'PrgR_Progression',
    'Gls_Per 90 Minutes',
    'Ast_Per 90 Minutes',
    'G+A_Per 90 Minutes',
    'G-PK_Per 90 Minutes',
    'G+A-PK_Per 90 Minutes',
    'xG_Per 90 Minutes',
    'xAG_Per 90 Minutes',
    'xG+xAG_Per 90 Minutes',
    'npxG_Per 90 Minutes',
    'npxG+xAG_Per 90 Minutes',
    '90s',
    'Touches_Touches',
    'Def Pen_Touches',
    'Def 3rd_Touches',
    'Mid 3rd_Touches',
    'Att 3rd_Touches',
    'Att Pen_Touches',
    'Live_Touches',
    'Att_Take-Ons',
    'Succ_Take-Ons',
    'Succ%_Take-Ons',
    'Tkld_Take-Ons',
    'Tkld%_Take-Ons',
    'Carries_Carries',
    'TotDist_Carries',
    'PrgDist_Carries',
    'PrgC_Carries',
    '1/3_Carries',
    'CPA_Carries',
    'Mis_Carries',
    'Dis_Carries',
    'Rec_Receiving',
    'PrgR_Receiving',
    'SCA_SCA',
    'SCA90_SCA',
    'PassLive_SCA Types',
    'PassDead_SCA Types',
    'TO_SCA Types',
    'Sh_SCA Types',
    'Fld_SCA Types',
    'Def_SCA Types',
    'GCA_GCA',
    'GCA90_GCA',
    'PassLive_GCA Types',
    'PassDead_GCA Types',
    'TO_GCA Types',
    'Sh_GCA Types',
    'Fld_GCA Types',
    'Def_GCA Types',
    'Cmp_Total',
    'Att_Total',
    'Cmp%_Total',
    'TotDist_Total',
    'PrgDist_Total',
    'Cmp_Short',
    'Att_Short',
    'Cmp%_Short',
    'Cmp_Medium',
    'Att_Medium',
    'Cmp%_Medium',
    'Cmp_Long',
    'Att_Long',
    'Cmp%_Long',
    'Ast',
    'xAG',
    'xA',
    'A-xAG',
    'KP',
    '1/3',
    'PPA',
    'CrsPA',
    'PrgP',
    'Gls_Standard',
    'Sh_Standard',
    'SoT_Standard',
    'SoT%_Standard',
    'Sh/90_Standard',
    'SoT/90_Standard',
    'G/Sh_Standard',
    'G/SoT_Standard',
    'Dist_Standard',
    'FK_Standard',
    'PK_Standard',
    'PKatt_Standard',
    'npxG/Sh_Expected',
    'G-xG_Expected',
    'np:G-xG_Expected',
    'Att',
    'Live_Pass Types',
    'Dead_Pass Types',
    'FK_Pass Types',
    'TB_Pass Types',
    'Sw_Pass Types',
    'Crs_Pass Types',
    'TI_Pass Types',
    'CK_Pass Types',
    'In_Corner Kicks',
    'Out_Corner Kicks',
    'Str_Corner Kicks',
    'Cmp_Outcomes',
    'Off_Outcomes',
    'Blocks_Outcomes',
    '2CrdY_Performance',
    'Fls_Performance',
    'Fld_Performance',
    'Off_Performance',
    'Crs_Performance',
    'Int_Performance',
    'TklW_Performance',
    'PKwon_Performance',
    'PKcon_Performance',
    'OG_Performance',
    'Recov_Performance',
    'Won_Aerial Duels',
    'Lost_Aerial Duels',
    'Won%_Aerial Duels'
]

rename_cols = [
    'Player',
    'Nation',
    'Pos',
    'Squad',
    'Age',
    'Born',
    'MP Playing Time',
    'Starts',
    'Min Playing Time',
    '90s Playing Time',
    'Goal',
    'Assist',
    'Goal+Assist',
    'Goal-PK',
    'PK',
    'PK Attempt',
    'Yellow Card',
    'Red Card',
    'xG',
    'npxG',
    'xA',
    'npxG+xA',
    'Progressive Carry',
    'Progressive Pass',
    'Progressive Receive',
    'Goal Per90',
    'Assist Per90',
    'G+A Per90',
    'G-PK Per90',
    'G+A-PK Per90',
    'xG Per90',
    'xA Per90',
    'xG+xA Per90',
    'npxG Per90',
    'npxG+xA Per90',
    '90s',
    'Touches',
    'Def-Pen\nTouch',
    'Def-3rd\nTouch',
    'Mid-3rd\nTouch',
    'Att-3rd\nTouch',
    'Att-Pen\nTouch',
    'Live Touch',
    'Dribble Attempt',
    'Successful\nDribble',
    'Successful%\nDribble',
    'Tackled\nDribble',
    'Tackled%\nDribble',
    'Carries',
    'Total-Distance\nCarries',
    'Progressive-Distance\nCarries',
    'Progressive\nCarries',
    '1/3 Carries',
    'Pena Carries',
    'Miscontrol',
    'Ball Lost',
    'Pass Receiving',
    'Progressive-Pass\nReceiving',
    'Shot Create',
    'Shot Create90',
    'Shot Create\nBy PassLive',
    'Shot Create\nBy PassDead',
    'Shot Create\nBy Dribble',
    'Shot Create\nBy Shot',
    'Shot Create\nBy Fouls',
    'Shot Create\nBy Deffense',
    'Goal Create',
    'Goal Create90',
    'Goal Create\nBy PassLive',
    'Goal Create\nBy PassDead',
    'Goal Create\nBy Dribble',
    'Goal Create\nBy Shot',
    'Goal Create\nBy Fouls',
    'Goal Create\nBy Deffense',
    'Pass Complete',
    'Pass Attempt',
    'Pass Complete%',
    'Pass Total Distance',
    'Progressive-Pass\nTotal Distance',
    'Short-Pass\nComplete',
    'Short-Pass\nAttempt',
    'Short-Pass\nComplete%',
    'Medium-Pass\nComplete',
    'Medium-Pass\nAttempt',
    'Medium-Pass\nComplete%',
    'Long-Pass\nComplete',
    'Long-Pass\nAttempt',
    'Long-Pass\nComplete%',
    'Assist',
    'xAG',
    'xA',
    'A-xAG',
    'KP',
    '1/3',
    'PPA',
    'CrsPA',
    'PrgP',
    'Gls_Standard',
    'Sh_Standard',
    'SoT_Standard',
    'SoT%_Standard',
    'Sh/90_Standard',
    'SoT/90_Standard',
    'G/Sh_Standard',
    'G/SoT_Standard',
    'Dist_Standard',
    'FK_Standard',
    'PK_Standard',
    'PKatt_Standard',
    'npxG/Sh_Expected',
    'G-xG_Expected',
    'np:G-xG_Expected',
    'Att',
    'Live Pass',
    'Dead Pass',
    'FK Pass',
    'Throwgh Pass',
    'Switch Pass',
    'Cross',
    'TI Pass',
    'CK Pass',
    'In_Corner Kicks',
    'Out_Corner Kicks',
    'Str_Corner Kicks',
    'Cmp_Outcomes',
    'Off_Outcomes',
    'Blocks_Outcomes',
    '2CrdY_Performance',
    'Fls_Performance',
    'Fld_Performance',
    'Off_Performance',
    'Crs_Performance',
    'Int_Performance',
    'TklW_Performance',
    'PKwon_Performance',
    'PKcon_Performance',
    'OG_Performance',
    'Recov_Performance',
    'Won_Aerial Duels',
    'Lost_Aerial Duels',
    'Won%_Aerial Duels'
]
